development:
  site_name: Along the Gringo Trail
  map:
    latitude: -16
    longitude: -57
    zoom: 3
    plan: >
      I'm starting in Bogota and plan on working my way south from there. My
      mom is meeting me in Lima in mid-Febrary and we're going to travel Peru for
      a few weeks.  After that, I'll continue on to Bolivia. Below is a map of 
      one version of the Gringo Trail, which is a sequence of places that backpackers 
      tend to visit.  I'm not sure I'll make it as far south as that route goes and I might not
      make it all the way to Rio. I'll probably purchase a return ticket after two
      or three months.
production:
  site_name: Along the Gringo Trail
  map:
    latitude: -16
    longitude: -57
    zoom: 3
    plan: >
      I'm starting in Bogota and plan on working my way south from there. My
      mom is meeting me in Lima in mid-Febrary and we're going to travel Peru for
      a few weeks.  After that, I'll continue on to Bolivia. Below is a map of 
      one version of the Gringo Trail, which is a sequence of places that backpackers 
      tend to visit.  I'm not sure I'll make it as far south as that route goes and I might not
      make it all the way to Rio. I'll probably purchase a return ticket after two
      or three months.

